development: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: db

test:
  <<: *default
  database: web_test